version: 2
jobs:
  build:
    docker:
      - image: wxishiko/ubuntu-wxwidgets-build:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: wxColumn sample build
          working_directory: samples/column
