version: 2
jobs:
  build:
    docker:
      - image: wxishiko/ubuntu-wxwidgets-build:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: wxAreaChart sample build
          command: make
          working_directory: samples/areachart
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxColumn sample build
          command: make
          working_directory: samples/column
          environment:
            WXCHARTS_ROOT: ../..
