version: 2
jobs:
  build:
    docker:
      - image: wxishiko/ubuntu-wxwidgets-build:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: wxAreaChart sample build
          command: make
          working_directory: samples/areachart
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxBar sample build
          command: make
          working_directory: samples/bar
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxBubble sample build
          command: make
          working_directory: samples/bubble
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxCandlestick sample build
          command: make
          working_directory: samples/candlestick
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxColumn sample build
          command: make
          working_directory: samples/column
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxCombinationChart sample build
          command: make
          working_directory: samples/combinationchart
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxDoughnut sample build
          command: make
          working_directory: samples/doughnut
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxHistogramChart sample build
          command: make
          working_directory: samples/histogram
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxLine sample build
          command: make
          working_directory: samples/line
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxMath2D sample build
          command: make
          working_directory: samples/math2d
          environment:
            WXCHARTS_ROOT: ../..
      - run:
          name: wxMath2DInteractive sample build
          command: make
          working_directory: samples/math2dinteractive
          environment:
            WXCHARTS_ROOT: ../..
