version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: LS
          command: ls
      - run:
          name: Build
          command: make .
